### ISSUE TITLE
OCB: StartImage failed - Aborted

### ISSUE THREAD

**Issue by alkanna** [gajosr/gigabyte-z390-aorus-master-hackintosh#1]
Hey, I am successfully using cmer's EFI, I am now trying yours to update OC to 0.6.7, however I am hitting this error when booting.

Is there something I missed ?

**Comment by gajosr** [comment]
Hey, you must check if your configuration is the same as mine and double check BIOS settings. 
You should also try to calculate your own slide value - this is different compared to cmer's EFI. 
Check this: https://dortania.github.io/OpenCore-Install-Guide/extras/kaslr-fix.html
I am using slide=167 in boot-args but in your configuration this can be different value.
You can change slide value to 0 and check if this will help.

**Comment by gajosr** [comment]
@alkanna On each BIOS update You should check slide value, it may be different for different BIOS versions and hardware configurations.

**Comment by gajosr** [comment]
@alkanna just updated to OC 0.7.0, no issues so far, you may try.
